name: Pull Request Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Install ğŸ¤–
        run: yarn
      - name: Build ğŸ‘·â€â™€ï¸
        run: yarn build
      - name: Lint ğŸ‘®â€â™€ï¸
        run: yarn lint
      - name: Test ğŸ™
        run: yarn test
